sudo: required
dist: trusty

language: node_js
node_js:
  - '6'

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update -q
  - sudo apt-get install -q google-chrome-stable

deploy:
  provider: heroku
  api_key:
    secure: "fa924b90-5969-4f79-9b2b-0afb6f8a75a8"
    app: "desafio-front-leo"
    
before_script:
  - npm install

script:
  - npm run test-single-run
